### ISSUE TITLE
StartPartitionDataLossAsync causes an issue

### ISSUE THREAD

**Issue by loekd** [loekd/ServiceFabric.BackupRestore#4]
calling this:
```
       var partitionSelector = PartitionSelector.PartitionIdOf(ServiceUri, partitionID);
       await new FabricClient(FabricClientRole.Admin).TestManager.StartPartitionDataLossAsync(Guid.NewGuid(), partitionSelector, DataLossMode.FullDataLoss);
```
                  
results in an error:

System.Fabric.FabricException: An error occurred during this operation. Please check the trace logs for more details. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071D0A
at System.Fabric.Interop.NativeClient.IFabricTestManagementClient3.EndStartPartitionDataLoss(IFabricAsyncOperationContext context)
at System.Fabric.Interop.Utility.<>c__DisplayClass20_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)

**Comment by loekd** [comment]
Can anyone repro this error?

**Comment by loekd** [comment]
closed; preview issue
